sudo: required
services:
  - docker

before_install:
  - docker build -t heerasinghmca07/react_test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true heerasinghmca07/react_test npm test -- --coverage

after_success:
  - docker build -t heerasinghmca07/multi_client ./client
  - docker build -t heerasinghmca07/multi_nginx  ./nginx
  - docker build -t heerasinghmca07/multi_server ./server
  - docker build -t heerasinghmca07/multi_worker ./worker

  # Login into Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker hub
  - docker push heerasinghmca07/multi_client
  - docker push heerasinghmca07/multi_nginx
  - docker push heerasinghmca07/multi_server
  - docker push heerasinghmca07/multi_worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-547742296786"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"